# fly.toml app configuration file generated for backend-copy on 2024-04-08T16:01:06+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'backend-copy'
primary_region = 'bos'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
